language: java
jdk:
- oraclejdk8
before_install:
  - mysql -e 'create database jleague13 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'
script: mvn clean install
deploy:
  - provider: codedeploy
    bucket: ru.alterloki.page-download
    key: page-download-app.zip
    application: page-download
    deployment_group: page-download_dep_group
    region: eu-central-1
    secret_access_key:
      secure: rB6OH9ELsNf13RKuSQBb1/FcxQED8jMNNpaHXOU4W5b+0xjQJx9EDRFLWblIWog9yxyd2k8z+uihb2j67AH6DyK3WPGOTgQPaR9w4fih9YM4aToh/wSih2giRhXpTgkh3/7FMPMNQGrowufTy0WQVwXaf6tAcOkq9UHPPx84SONjH4uudlLOZrBnpYTm6TbhVgLc9syNncYwqUrIpJkoGu+OnnalOrrZrKghiw6ZzxOKmS3K/WfI0QsgxLRDdfLyBpeG3D2EJBlLAO4Rgu/4SoSQhRxAfzACyZsCqrXAx/ffMCkjo6DDV0OU2kDBLlQIUcsrris/wGr5FZdWoOP8p4fQpTRzHDFAco9VQmON+vKC7ZP9iRpxFxIqnFBrjpU9FWSpjpPTw3lnElwiKpwegsrGxnGzufwRf3OoZfFYkmqkAwz3ZTcT3mTE8jHXmFgHNhoP1htjKOJo9JV9VhlmiaQvd14rdmbLi4Zr36FObnjLhUhadGu7NMq9AnAciDoXBIjapNDlTYzYtJrdg9v9OaFv85Fj61Byaqkbm9RxhP3BUc7D6ZAWM7zK33YUkP9y3HQrVUhA1PsO+230t3ZF99UB5tIu3i1sgJHgrfWSChrgPuh/OVcSK7czlUammvNREZMl5FkJBzqTV3Xf/piBUoz/2xyKt72aDLTiqZRiBL8=
    access_key_id:
      secure: J8vtAeCFT73+N1dYOYwldJr5swgeo2HHzKBNSnpONXMAIjvC7t8CkGfaW8xHWWiehUjWlsrPJEiBji8oK5weAr/h6NKa9ko7U9KvneAIvXqZB/9zkxdqh1zi902fIJZsR1/SVSv53XUPHgcKv5JuoKWAnH1AROP60VUmWolCs68RkkcZKr1IDdG4ClBM1VEAeQZert9GR4CxSu250GRoD1fteSjSUs8jwHjwQ0qpxBTsPzlmLxY7RInhVa1vl40xJEnTFH35LtMMoIA3Q39CCjs77Wzmb0V86TWHdwNHG4L91ytVIbjpIpAmjE9zUh+80am2Ncw/HgPii5rh2Sse79mBu2qCBYEFZJzlA1KgbYN8Mp5l/xeQ2xndNlF8kRr3re1VG19h/XEuft84ThpXoq3qS/nmZY15B65SwJpwqz33fOEWzCAW28iVZ0uE1doYObza3kEPoQs7YzjL0Gtp8IM+vCyYkaQ3WKHz2Zykpq1kl3lXPgS2atcmaiFCz31V/sptBYn1TSYN/TYZrcWKS9XWODBm1YR0xuNgl9dGXhDnL7f/wdY6yrG6AyKS+p1cgJ4lc+xfL9qPIgvUTWngSN/WYHVVfFYEbKsk/Lfoh9ab++i62m4lyLq4mukPODCHUDnwAGEL9JU3BTLivjWJCfaxR2T1pRwsgOK+2VWSEpw=
